### ISSUE TITLE
Text not visible on MacOS Mojave

### ISSUE THREAD

**Issue by navanchauhan** [M4cs/EGTR-FutureRestore#3]
<img width="493" alt="screenshot 2019-02-01 at 1 38 39 pm" src="https://user-images.githubusercontent.com/29234112/52110481-c0fe1300-2626-11e9-9d56-bdbd85b1f9fb.png">

Installed all requirements and running egtr.py via `python3 egtr.py`

**Comment by electimon** [comment]
Check the terminal, is there any output?

**Comment by M4cs** [comment]
^ any errors in terminal would be appreciated. try changing to `PySimpleGUI` rather than `PySimpleGUIQt`. You'll have to run `pip install PySimpleGUI`

**Comment by navanchauhan** [comment]
> Check the terminal, is there any output?



> ^ any errors in terminal would be appreciated. try changing to `PySimpleGUI` rather than `PySimpleGUIQt`. You'll have to run `pip install PySimpleGUI`

Nope. No errors tried PySimpleGUI too
