### ISSUE TITLE
I get Segmentation Fault( Core Dumped) on Ubuntu 18.10

### ISSUE THREAD

**Issue by Nikostito** [M4cs/EGTR-FutureRestore#4]
Whenever I try running the python script I get seg fault. I have installed all requirements. Any help appreciated

**Comment by M4cs** [comment]
....well first of all this is super rare for a python program and I can tell you 100% it's your installation of python. Check out [this link](https://stackoverflow.com/questions/13654449/error-segmentation-fault-core-dumped) for more info.
